# Base16 Yoru - kitty color config
# Scheme adapted by Anonyma from the Yoru NvChad theme
background #0c0e0f
foreground #edeff0
selection_background #edeff0
selection_foreground #0c0e0f
url_color #709ad2
cursor #709ad2
cursor_text_color #0c0e0f
active_border_color #1f2122
inactive_border_color #121415
active_tab_background #0c0e0f
active_tab_foreground #edeff0
inactive_tab_background #121415
inactive_tab_foreground #27292a

# Normal
color0 #0c0e0f
color1 #f26e74
color2 #82c29c
color3 #e79881
color4 #709ad2
color5 #c58cec
color6 #6791C9
color7 #edeff0

# Bright (same as Normal except 8/15)
color8 #1f2122
color9 #f26e74
color10 #82c29c
color11 #e79881
color12 #709ad2
color13 #c58cec
color14 #6791C9
color15 #f2f4f5

# Other (like base16-shell)
color16 #ecd28b
color17 #e8646a
color18 #121415
color19 #161819
color20 #27292a
color21 #e4e6e7
